# Generated by Django 5.2.6 on 2025-09-18 20:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField(blank=True)),
                ('technologies', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('team_size', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be 4 digits', regex='^\\d{4}$')])),
                ('demo_video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_featured'], name='projects_is_feat_5ab0be_idx'), models.Index(fields=['sort_order'], name='projects_sort_or_cd3b3f_idx'), models.Index(fields=['year'], name='projects_year_6e1c07_idx'), models.Index(fields=['-created_at'], name='projects_created_390fdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'db_table': 'project_images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['project', 'is_primary'], name='project_ima_project_4c0d76_idx'), models.Index(fields=['project', 'sort_order'], name='project_ima_project_b674eb_idx')],
            },
        ),
    ]
