services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne portfolio_backend.asgi:application --port $PORT --bind 0.0.0.0
    plan: starter
    autoDeploy: false
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_backend.settings.production
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PIP_VERSION
        value: 23.2.1

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: starter